[versions]
kotlin = "2.2.0"
kotlinx-serialization = "1.8.1"

mongodb = "5.5.1"
mongokt = "0.2.0-beta.10"

[libraries]
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }

mongodb-sync = { module = "org.mongodb:mongodb-driver-sync", version.ref = "mongodb" }
mongodb-reactivestreams = { module = "org.mongodb:mongodb-driver-reactivestreams", version.ref = "mongodb" }

bsonkt = { module = "org.cufy.mongokt:bsonkt", version.ref = "mongokt" }
mongokt = { module = "org.cufy.mongokt:mongokt", version.ref = "mongokt" }
