[versions]
kotlin = "2.1.0"
kotlinx-serialization = "1.7.3"
kotlinx-coroutines = "1.9.0"
kotlinx-datetime = "0.6.1"

mongodb = "5.2.1"

mongokt = "0.1.2"

[libraries]
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }

mongodb-sync = { module = "org.mongodb:mongodb-driver-sync", version.ref = "mongodb" }
mongodb-reactivestreams = { module = "org.mongodb:mongodb-driver-reactivestreams", version.ref = "mongodb" }

bsonkt = { module = "org.cufy.mongokt:bsonkt", version.ref = "mongokt" }
